defaults:
  - default_disabled

algorithm: max
quant_cfg:
  '*weight_quantizer':
    num_bits: [4, 3]
    axis: 0
  '*input_quantizer':
    num_bits: [4, 3]
    type: dynamic
    block_sizes:
      -1: null
