defaults:
  - default_disabled

algorithm: null
quant_cfg:
  "*mlp*weight_quantizer":
    num_bits: [2, 1]
    block_sizes:
      -1: 32
      type: dynamic
      scale_bits: [8, 0]
    enable: true
    pass_through_bwd: true
