algorithm: max
quant_cfg:
  '*[kv]_bmm_quantizer':
    num_bits: [2, 1]
    block_sizes:
      -1: 16
      type: dynamic
      scale_bits: [4, 3]
    axis: null
    bias:
      -2: null
      -4: null
      type: static
    enable: true
  default:
    enable: false
