defaults:
  - default_disabled

algorithm: max
quant_cfg:
  '*weight_quantizer':
    block_sizes:
      -1: 16
      type: dynamic
      scale_bits: [4, 3]
    num_bits: [2, 1]
    axis: null
    enable: true
  '*input_quantizer':
    block_sizes:
      -1: 16
      type: dynamic
      scale_bits: [4, 3]
    num_bits: [2, 1]
    axis: null
    enable: true
