defaults:
  - default_disabled

algorithm: awq_lite
quant_cfg:
  '*weight_quantizer':
    - num_bits: 4
      block_sizes:
        -1: 128
        type: static
      enable: true

    - num_bits: [4, 3]
      axis: null
      enable: true

  '*input_quantizer':
    num_bits: [4, 3]
    enable: true
    axis: null
